name: TutorialPlugin
main: com.jwparks.movieplugin.Main
version: 0.0.1
description: Plugin for Minecraft Task Tutorial

commands:
  movie:
    description: Your description
    usage: /<command>
    permission: com.jwparks.movieplugin.MovieStart