name: TutorialPlugin
main: com.jwparks.tutorialplugin.Main
version: 0.0.1
description: Plugin for Minecraft Task Tutorial

commands:
  camera:
    description: Your description
    usage: /<command>
    permission: com.jwparks.tutorialplugin.CameraTutorialStart

  move:
    description: Your description
    usage: /<command>
    permission: com.jwparks.tutorialplugin.MoveTutorialStart

  easy:
    description: Your description
    usage: /<command>
    permission: com.jwparks.tutorialplugin.EasyTutorialStart

  hard:
    description: Your description
    usage: /<command>
    permission: com.jwparks.tutorialplugin.HardTutorialStart

  reset:
    description: Your description
    usage: /<command>
    permission: com.jwparks.tutorialplugin.ResetTutorialStart